services:
  - type: web
    name: cloud-instagram-manager
    runtime: python
    buildCommand: |
      storage_dir=/opt/render/project/.render
      if [ ! -d "$storage_dir/chrome" ]; then
        echo "Installing Google Chrome..."
        mkdir -p $storage_dir/chrome
        cd $storage_dir/chrome
        wget -q https://storage.googleapis.com/chrome-for-testing-public/125.0.6422.141/linux64/chrome-linux64.zip
        unzip -q chrome-linux64.zip
        wget -q https://storage.googleapis.com/chrome-for-testing-public/125.0.6422.141/linux64/chromedriver-linux64.zip
        unzip -q chromedriver-linux64.zip
      fi
      cd /opt/render/project/src
      pip install -r requirements.txt
    startCommand: gunicorn app:app
